Controllers/DispositivosController.cs
using System.Security.Claims;
using Examen_UII.Hubs;
using Examen_UII.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;

namespace Examen_UII.Controllers
{
    [Authorize]
    public class DispositivosController : Controller
    {
        private readonly AguaDBContext _db;

        private readonly IHubContext<NotificacionHub> _notificacionHubContext;

        public DispositivosController(AguaDBContext db, IHubContext<NotificacionHub> notificacionHubContext)
        {
            _db = db;
            _notificacionHubContext = notificacionHubContext;
        }


        public IActionResult Mapa()
        {
            int userId = Convert.ToInt32(User.FindFirstValue("userId"));

            List<Dispositivos> dispositivos;

            if (User.IsInRole("Admin"))
            {
                dispositivos = _db.Dispositivos.ToList();
            }
            else
            {
                dispositivos = _db.Dispositivos
                    .Where(d => d.UsuariosId == userId)
                    .ToList();
            }

            return View(dispositivos);
        }


        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Registrar()
        {
            var listaUsuarios = _db.Usuarios
                .Where(u => u.RolesId != 1)
                .Select(u => new SelectListItem
                {
                    Value = u.ID.ToString(),
                    Text = u.Nombre
                })
                .ToList();

            var listaZonas = _db.Zonas.Select(z => new SelectListItem
            {
                Value = z.ID.ToString(),
                Text = z.Nombre
            }).ToList();

            var listaEstados = _db.Estados.Select(e => new SelectListItem
            {
                Value = e.Id.ToString(),
                Text = e.Nombre
            }).ToList();

            ViewData["Usuarios"] = listaUsuarios;
            ViewData["Zonas"] = listaZonas;
            ViewData["Estados"] = listaEstados;

            ViewData["PrioridadOptions"] = new List<SelectListItem>
            {
                new SelectListItem("Baja", "1"),
                new SelectListItem("Media", "2"),
                new SelectListItem("Alta", "3")
            };

            return View();
        }


        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Registrar(Dispositivos dispositivo)
        {
            if (ModelState.IsValid)
            {
                if (dispositivo.EstadosId == 1)
                {
                    _db.Dispositivos.Add(dispositivo);

                    await _db.SaveChangesAsync();
                    var registroConsumo = new RegistrosConsumo
                    {
                        DispositivosId = dispositivo.ID,
                        Inicio = DateTime.Now
                    };
                    _db.RegistrosConsumo.Add(registroConsumo);

                    await _db.SaveChangesAsync();

                }
                else if (dispositivo.EstadosId == 2)
                {
                    _db.Dispositivos.Add(dispositivo);
                    await _db.SaveChangesAsync();

                }
                else
                {
                    return RedirectToAction("Error", "Usuarios");
                }
                

                List<Usuarios> admins = _db.Usuarios.Include(x => x.Roles).Where(x => x.RolesId == 1).ToList();
                if (admins.Any())
                {
                    await _notificacionHubContext.Clients.All.SendAsync("DeviceCreate", dispositivo.ID);
                }
                await _notificacionHubContext.Clients.All.SendAsync("DeviceStateChanged", dispositivo.ID, dispositivo.EstadosId);
                await _notificacionHubContext.Clients.All.SendAsync("AgregarATabla");
                return RedirectToAction("Consultar");

            }
            else
            {
                return RedirectToAction("Error", "Usuarios");
            }
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Consultar()
        {

            var dispositivos = _db.Dispositivos
            .Include(d => d.Usuarios)
            .Include(d => d.Zonas)
            .Include(d => d.Estados)
            .ToList();

            return View(dispositivos);

        }

        [HttpPost]
        public async Task<IActionResult> CambiarEstado(int id)
        {
            var dispositivo = await _db.Dispositivos.FindAsync(id);
            int userId = Convert.ToInt32(User.FindFirstValue("userId"));

            if (dispositivo != null)
            {
                if (dispositivo.UsuariosId == userId || User.IsInRole("Admin"))
                {
                    dispositivo.EstadosId = 1;

                    var nuevoRegistro = new RegistrosConsumo
                    {
                        DispositivosId = dispositivo.ID,
                        Inicio = DateTime.Now
                    };

                    _db.RegistrosConsumo.Add(nuevoRegistro);

                    await _db.SaveChangesAsync();
                    await _notificacionHubContext.Clients.All.SendAsync("DeviceStateChanged", dispositivo.ID, dispositivo.EstadosId);
                    List<Usuarios> admins = _db.Usuarios.Include(x => x.Roles).Where(x => x.RolesId == 1).ToList();
                    if (admins.Any())
                    {
                        await _notificacionHubContext.Clients.All.SendAsync("DeviceOpened", id);
                    }
                    return RedirectToAction("Mapa");

                }
                else
                {
                    return RedirectToAction("NoPermitido", "Usuarios");
                }
            }
            else
            {
                return RedirectToAction("Error", "Usuarios");
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Eliminar([FromBody] int id)
        {
            var dispositivo = await _db.Dispositivos.FindAsync(id);

            if (dispositivo != null)
            {
                _db.Dispositivos.Remove(dispositivo);
                await _db.SaveChangesAsync();

                List<Usuarios> admins = _db.Usuarios.Include(x => x.Roles).Where(x => x.RolesId == 1).ToList();
                if (admins.Any())
                {
                    await _notificacionHubContext.Clients.All.SendAsync("DeviceDelete", id);
                }

                return Ok(); 
            }
            else
            {
                return BadRequest("No se pudo encontrar el dispositivo"); 
            }
        }

        [Authorize(Roles = "Admin")]
        public IActionResult GraficaEstados()
        {
            return View();
        }

        public IActionResult ObtenerDatosDispositivos()
        {
            try
            {
                var dispositivosAbiertos = _db.Dispositivos.Count(d =>
                d.EstadosId == 1);
                var dispositivosCerrados = _db.Dispositivos.Count(d =>
                d.EstadosId == 2);
                var data = new
                {
                    Abiertos = dispositivosAbiertos,
                    Cerrados = dispositivosCerrados
                };
                var jsonData = Json(data);
                return jsonData;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al obtener datos de dispositivos: {ex.Message} ");
                return StatusCode(500, "Error interno del servidor");
            }
        }

        [Authorize(Roles = "Admin")]
        public IActionResult GraficaDatos()
        {
            return View();
        }

        public IActionResult ObtenerDatos()
        {
            try
            {
                var dispositivos = _db.Dispositivos.Include(d => d.RegistrosConsumo).ToList();
                var data = new List<object>();

                foreach (var dispositivo in dispositivos)
                {
                    var litrosRegistrados = dispositivo.RegistrosConsumo.Sum(r => r.CantidadLitrosRegistrados);
                    int estadoId = dispositivo.EstadosId;
                    int estado = estadoId == 1 ? 1 : 2;

                    var dispositivoData = new
                    {
                        Id = dispositivo.ID,
                        Prioridad = dispositivo.Prioridad,
                        Zona = dispositivo.ZonasId,
                        LitrosRegistrados = litrosRegistrados,
                        Estado = estado
                    };
                    data.Add(dispositivoData);
                }

                return Json(data);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al obtener datos de dispositivos: {ex.Message}");
                return StatusCode(500, "Error interno del servidor");
            }
        }

        public IActionResult ErrorD()
        {
            return View();
        }

        public async Task<IActionResult> GetDispositivos()
        {
            return Json(await _db.Dispositivos.ToListAsync());
        }

    }
}

Controllers/RegistrosConsumoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Examen_UII.Hubs;
using Examen_UII.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Examen_UII.Controllers
{
    [Authorize]
    public class RegistrosConsumoController : Controller
    {
        private readonly AguaDBContext _db;
        private readonly IHubContext<MapHub> _hubContext;

        private readonly IHubContext<NotificacionHub> _notificacionHubContext;

        public RegistrosConsumoController(AguaDBContext db, IHubContext<MapHub> hubContext, IHubContext<NotificacionHub> notificacionHubContext)
        {
            _db = db;
            _hubContext = hubContext;
            _notificacionHubContext = notificacionHubContext;
        }

        [HttpGet]
        public IActionResult Registrar(int dispositivoId)
        {
            ViewData["DispositivosId"] = dispositivoId;
            return View();
        }

        public async Task<IActionResult> Registrar(RegistrosConsumo registros)
        {
            if (ModelState.IsValid)
            {
                registros.Fin = DateTime.Now;
                int userId = Convert.ToInt32(User.FindFirstValue("userId"));
                var dispositivo = await _db.Dispositivos.FindAsync(registros.DispositivosId);

                if (dispositivo != null)
                {
                    if (dispositivo.UsuariosId == userId || User.IsInRole("Admin"))
                    {
                        var ultimoAbierto = _db.Dispositivos.Count(d => d.EstadosId == 1) == 1 && dispositivo.EstadosId == 1;

                        if (ultimoAbierto)
                        {
                            List<Usuarios> adminsList = _db.Usuarios.Include(x => x.Roles).Where(x => x.RolesId == 1).ToList();
                            if (adminsList.Any())
                            {
                                await _notificacionHubContext.Clients.All.SendAsync("NotificacionCerrarUltimo", "No puedes cerrar el último dispositivo abierto.");
                            }

                            return RedirectToAction("Mapa", "Dispositivos");
                        }

                        var registroExistente = await _db.RegistrosConsumo
                            .Where(r => r.DispositivosId == registros.DispositivosId)
                            .OrderByDescending(r => r.Inicio)
                            .FirstOrDefaultAsync();

                        if (registroExistente != null)
                        {
                            registroExistente.Fin = registros.Fin;
                            registroExistente.CantidadLitrosRegistrados = registros.CantidadLitrosRegistrados;
                        }
                        else
                        {
                            return RedirectToAction("Error", "Usuarios");
                        }

                        dispositivo.EstadosId = 2;

                        await _db.SaveChangesAsync();
                        await _notificacionHubContext.Clients.All.SendAsync("DeviceStateChanged", dispositivo.ID, dispositivo.EstadosId);
                        List<Usuarios> admins = _db.Usuarios.Include(x => x.Roles).Where(x => x.RolesId == 1).ToList();
                        if (admins.Any())
                        {
                            await _notificacionHubContext.Clients.All.SendAsync("DeviceClosed", registros.DispositivosId);
                        }
                        return RedirectToAction("Mapa", "Dispositivos");
                    }
                    else
                    {
                        return RedirectToAction("NoPermitido", "Usuarios");
                    }
                }
            }
            return View(registros);
        }


        public IActionResult Consultar()
        {
            int userId = Convert.ToInt32(User.FindFirstValue("userId"));
            if (User.IsInRole("Admin"))
            {
                var registros = _db.RegistrosConsumo
                    .Include(r => r.Dispositivos)
                    .ToList();
                return View(registros);
            }
            else
            {
                var registros = _db.RegistrosConsumo
                    .Include(r => r.Dispositivos)
                    .Where(r => r.Dispositivos.UsuariosId == userId)
                    .ToList();
                return View(registros);
            }
        }


        [Authorize(Roles = "Admin")]
        public IActionResult GraficaConsumo()
        {
            return View();
        }
        public IActionResult ObtenerLitros()
        {
            try
            {
                var totalLitrosRegistrados = _db.RegistrosConsumo.Sum(r =>
                r.CantidadLitrosRegistrados);
                var data = new
                {
                    TotalLitrosRegistrados = totalLitrosRegistrados
                };
                return Json(data);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al obtener datos de dispositivos: {ex.Message}");
                return StatusCode(500, "Error interno del servidor");
            }
        }

    }
}

Controllers/UsuariosController.cs
using System.Security.Claims;
using Examen_UII.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace _2._5_WebSockets.Controllers
{
    public class UsuariosController : Controller
    {

        private readonly AguaDBContext context;

        public UsuariosController(AguaDBContext context)
        {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Usuarios u)
        {

            if (ModelState.IsValid)
            {
                Usuarios utemp = context.Usuarios.Include(x => x.Roles)
                                .FirstOrDefault(x => x.Usuario == u.Usuario
                                && x.Password == u.Password)!;
                if (utemp != null)
                {
                    List<Claim> claims = new List<Claim>();
                    claims.Add(new Claim("userId", utemp.ID.ToString()));
                    claims.Add(new Claim("username", utemp.Usuario!));
                    claims.Add(new Claim(ClaimTypes.NameIdentifier, utemp.Usuario!));
                    claims.Add(new Claim(ClaimTypes.Role, utemp.Roles.Rol));
                    ClaimsIdentity identity = new ClaimsIdentity(claims,
                        CookieAuthenticationDefaults.AuthenticationScheme);
                    ClaimsPrincipal principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(principal);
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Error = "Usuario y/o password incorrectos";
            return View(u);
        }

        [Authorize]
        public IActionResult Index()
        {
            var username = User.FindFirstValue(ClaimTypes.NameIdentifier); 
            ViewData["UserName"] = username; 
            return View();
        }

        [Authorize]
        public IActionResult NoPermitido()
        {
            return View();
        }

        [Authorize]
        public IActionResult Error()
        {
            return View();
        }

        [Authorize]
        public async Task<IActionResult> CerrarSesion()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Examen_UII</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/Examen_UII.styles.css" asp-append-version="true" /> *@
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Usuarios" asp-action="Index">Examen_UII</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>


                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link active" asp-action="Index" asp-controller="Usuarios">Inicio</a>
                            </li>

                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown"
                                        aria-expanded="false">
                                        Dispositivos
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" asp-action="Consultar"
                                                asp-controller="Dispositivos">Tabla</a></li>

                                        <li><a class="dropdown-item" asp-action="Mapa" asp-controller="Dispositivos">Mapa</a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown"
                                        aria-expanded="false">
                                        Graficas
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" asp-action="GraficaDatos"
                                                asp-controller="Dispositivos">Datos</a></li>

                                        <li><a class="dropdown-item" asp-action="GraficaEstados"
                                                asp-controller="Dispositivos">Estados</a></li>

                                        <li><a class="dropdown-item" asp-action="GraficaConsumo"
                                                asp-controller="RegistrosConsumo">Consumo</a></li>
                                    </ul>
                                </li>

                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link active" asp-action="Mapa" asp-controller="Dispositivos">Cambiar
                                        Estados</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link active" asp-controller="RegistrosConsumo"
                                    asp-action="Consultar">Registros de consumo</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link active" asp-action="CerrarSesion" asp-controller="Usuarios">Cerrar
                                    Sesión</a>
                            </li>
                        }
                        else
                        {

                            <li class="nav-item">
                                <a class="nav-link active" asp-action="Login" asp-controller="Usuarios">Iniciar Sesión</a>
                            </li>
                        }

                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Examen_UII - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @if (User.Identity.IsAuthenticated)
    {
        @if (User.IsInRole("Admin"))
        {
            <script src="~/js/SignalR.js"></script>

            <script>
                var connection = new signalR.HubConnectionBuilder()
                    .withUrl("/notificacionHub")
                    .build();

                connection.start().then(function () {
                    console.log("Conexión de SignalR establecida.");
                }).catch(function (err) {
                    console.error("Error de conexión SignalR: " + err);
                });

                connection.on("DeviceCreate", function (dispositivoId) {
                    MostrarNotificaciones(`El dispositivo ${dispositivoId} se ha creado.`);
                });

                connection.on("DeviceDelete", function (dispositivoId) {
                    MostrarNotificaciones(`El dispositivo ${dispositivoId} se ha eliminado.`);
                });

                connection.on("DeviceOpened", function (dispositivoId) {
                    MostrarNotificaciones(`El dispositivo ${dispositivoId} se ha abierto.`);
                });

                connection.on("DeviceClosed", function (dispositivoId) {
                    MostrarNotificaciones(`El dispositivo ${dispositivoId} se ha cerrado.`);
                });

                connection.on("NotificacionCerrarUltimo", function (mensaje) {
                    MostrarNotificaciones(mensaje);
                });

                function MostrarNotificaciones(msj) {
                    if (!(Notification) in window) {
                        alert("El navegador no soporta notificaciones");
                    }
                    else if (Notification.permission === "granted") {
                        const noti = new Notification(msj);

                    }
                    else if (Notification.permission !== "denied") {
                        Notification.requestPermission(function (p) {
                            if (Notification.permission === "granted") {
                                const ns = new Notification("Permiso autorizado");
                            }
                        });
                    }
                }
            </script>
        }
    }
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>